### PR TITLE
Fix inconsistent newsletter form background to match dark mode

### PR DESCRIPTION
**Pull request by PATILYASHH**
## _Before_

image

## _After_

image

---
### Issue no : #51

### CODE REVIEW

**Comment by Praneeth8888** [comment]
yeah , it looks better now

**Comment by PATILYASHH** [comment]
> yeah , it looks better now

Is it really looking good or you just making fun of it ??

**Comment by Praneeth8888** [comment]
> > yeah , it looks better now
> 
> Is it really looking good or you just making fun of it ??

no no , i wanted to fix it , you already did , so i appreciated you.

**Comment by PATILYASHH** [comment]
> > > yeah , it looks better now
> > 
> > Is it really looking good or you just making fun of it ??
> 
> no no , i wanted to fix it , you already did , so i appreciated you.

Thank you

**Pull request closed without merging**
